image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview
  - port: 2222
    onOpen: ignore
  - port: 8080
    onOpen: ignore
tasks:
    command: echo "Lets do this" 
    name: Rails
